export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://halskollen.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/vitaminer","priority":"0.8","changefreq":"weekly"},{"path":"/kosttillskott","priority":"0.8","changefreq":"weekly"},{"path":"/vegansk","priority":"0.8","changefreq":"weekly"},{"path":"/sport","priority":"0.8","changefreq":"weekly"},{"path":"/online","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-bodystore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-proteinbolaget","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-iherb","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-holland-barrett","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-sportamore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/gymgrossisten-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-proteinbolaget","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-iherb","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-holland-barrett","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-sportamore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bodystore-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proteinbolaget-vs-iherb","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proteinbolaget-vs-holland-barrett","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proteinbolaget-vs-sportamore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proteinbolaget-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/proteinbolaget-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/iherb-vs-holland-barrett","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/iherb-vs-sportamore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/iherb-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/iherb-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/holland-barrett-vs-sportamore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/holland-barrett-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/holland-barrett-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sportamore-vs-vitaminstore","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sportamore-vs-nyttoteket","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/vitaminstore-vs-nyttoteket","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-23</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }